Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/jammy64"   
  config.vm.hostname = "jenkins"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 8091, host: 8091, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "6144" # Aloca 6GB de RAM para a VM
  end
  config.vbguest.auto_update = false

end
