Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/jammy64"   
  config.vm.hostname = "jenkins"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096" # Aloca 4GB de RAM para a VM
  end
  config.vbguest.auto_update = false

end
