Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"   # Ubuntu 20.04 LTS
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder "./html", "/vagrant/html"

  config.vbguest.auto_update = false

  config.vm.provision "shell", path: "provision.sh"
end
