Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname="db01"
  config.vm.network "private_network", ip: "192.168.56.12"
  config.vm.network "forwarded_port", guest: 3306, host: 4444

  config.vbguest.auto_update = false

end
